version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes: #掛載 前面是虛擬機映射的:後面是docker container內的
      - /home/tayli_club/nginx/html:/usr/share/nginx/html
      - /home/tayli_club/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true #nginx權限調用問題
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  demoProject:
    image: demo-project:latest
    build: . #當前目錄下build 把dockerfile 的jar build出來到容器裡
    ports:
      - 7998:7998